# Generated by Django 5.2.3 on 2025-07-01 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='uname',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
