# Generated by Django 5.2.4 on 2025-07-11 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='uname',
        ),
    ]
