# Generated by Django 4.2.20 on 2025-08-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
