# Generated by Django 5.2.3 on 2025-07-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='startPrice',
            field=models.IntegerField(default=0),
        ),
    ]
