# Generated by Django 5.2.4 on 2025-07-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_bids_date_alter_auction_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
