# Generated by Django 5.2.4 on 2025-07-25 22:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_bidlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
