# Generated by Django 5.2.3 on 2025-06-26 22:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
