# Generated by Django 5.2.4 on 2025-07-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='access_token',
            field=models.CharField(default='NO_ACCESS_TOKEN_YET', max_length=150),
        ),
    ]
