from django.contrib import admin
from .models import Post
# Register your models here.

#Allows you to edit the Post database through the admin page that is generated by Django
admin.site.register(Post)