# Generated by Django 5.2.4 on 2025-07-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
    ]
