# Generated by Django 5.2.4 on 2025-07-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_room_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_song',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
