# Generated by Django 5.2.4 on 2025-07-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_room_admit_required_requests_userinroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='user_requesting',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinroom',
            name='user',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
