# Generated by Django 5.2.4 on 2025-07-31 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_requests_user_requesting_alter_userinroom_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInRoom',
            new_name='UsersInRoom',
        ),
    ]
