# Generated by Django 5.2.4 on 2025-07-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_userinroom_usersinroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='admit_required',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
