# Generated by Django 5.2.4 on 2025-07-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_room_admit_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersinroom',
            name='user_code',
            field=models.IntegerField(default=78060118),
        ),
    ]
