# Generated by Django 5.2.4 on 2025-07-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_usersinroom_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersinroom',
            name='user_code',
            field=models.IntegerField(default=48465470, unique=True),
        ),
    ]
