# Generated by Django 5.2.4 on 2025-08-01 03:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_usersinroom_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersinroom',
            name='user_code',
            field=models.IntegerField(default=api.models.generate_unique_number, unique=True),
        ),
    ]
